spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/happening

proximity:
  geohash:
    precision: 6
    node:
      capacity: 1000

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG